### ISSUE TITLE
Should cmd_states have an off-nominal roll column?

### ISSUE THREAD

**Issue by jeanconn** [sot/cmd_states#25]
It is a derived parameter, but so is pitch and we've got that in the database.  

And if we don't add the column, should the code to compute off nominal roll over a set of states live in cmd_states?

**Comment by taldcroft** [comment]
This can be computed on-the-fly.  It certainly seems reasonable to do so by introducing the concept of computed state columns.

**Comment by taldcroft** [comment]
And I should have said the same thing about pitch years ago...
