### ISSUE TITLE
decode_power not giving all information

### ISSUE THREAD

**Issue by jzuhone** [sot/cmd_states#34]
@jeanconn it appears that when the changes were made to `decode_power` in PR #31 (resulting in version 3.13) that the state of `vid_board` and `clocking` are no longer returned:

```python
decode_power("WSPOW04F3E")
```

gives

```pycon
{'ccd_count': 5,
 'ccds': 'I0 I1 I2 I3 S2 ',
 'fep_count': 5,
 'feps': '1 2 3 4 5 '}
```

similarly,

```python
decode_power('WSPOW00000')
```

gives

```pycon
{'ccd_count': 0, 'ccds': '', 'fep_count': 0, 'feps': ''}
```

But looking at the code, it's not obvious why this should happen.

**Comment by jzuhone** [comment]
@jeanconn false alarm--sorry, my dumb mistake. I was on the wrong version of `cmd_states`. Closing this issue.

**Comment by jeanconn** [comment]
@jzuhone  No sweat; part of the problem is that for this old code there isn't great unit test coverage so it isn't easy to verify that something is actually working...
